#!/usr/bin/env bash
# tui/modules/backup/launcher.sh - 生成 / 删除 xynrin-launch-* 启动器
# Create / remove xynrin-launch-* launcher shortcuts in $PREFIX/bin

# 校验启动器名后缀：只允许 [A-Za-z0-9._-]，避免出现路径分隔或空格
# Validate launcher name suffix: only [A-Za-z0-9._-] to avoid path tricks / spaces
_backup_launcher_name_ok() {
    [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]
}

backup_launcher_create() {
    backup_require_proot || return 1

    local installed
    installed="$(list_installed_distros)"
    if [[ -z "$installed" ]]; then
        log_warn "${MSG_PROOT_NOT_INSTALLED:-No proot distros installed}"
        return 0
    fi

    local distro
    if command -v fzf &> /dev/null; then
        distro="$(echo "$installed" | fzf --height=50% --reverse --no-info --border=rounded \
            --prompt="${MSG_BACKUP_LAUNCH_DISTRO:-Pick distro for launcher} > ")" || return 0
    else
        echo "$installed"
        echo -n "> "
        read -r distro
    fi
    [[ -z "$distro" ]] && return 0

    log_info "${MSG_BACKUP_LAUNCH_NAME_HINT:-Launcher name suffix (final command will be xynrin-launch-<name>)}"
    echo -n "name> "
    local raw_name
    read -r raw_name
    [[ -z "$raw_name" ]] && { log_warn "${MSG_INVALID_CHOICE:-Invalid choice}"; return 1; }
    if ! _backup_launcher_name_ok "$raw_name"; then
        log_err "${MSG_BACKUP_LAUNCH_BAD_NAME:-Name may only contain letters, digits, dot, underscore, dash}"
        return 1
    fi

    log_info "${MSG_BACKUP_LAUNCH_CMD_HINT:-Command to run inside the container (e.g. bash, startxfce4, code)}"
    echo -n "cmd> "
    local cmd
    read -r cmd
    [[ -z "$cmd" ]] && { log_warn "${MSG_INVALID_CHOICE:-Invalid choice}"; return 1; }

    local launcher_path="$BACKUP_BIN_DIR/${BACKUP_LAUNCH_PREFIX}${raw_name}"

    if [[ -e "$launcher_path" ]]; then
        log_warn "${MSG_BACKUP_LAUNCH_EXISTS:-Launcher already exists}: $launcher_path"
        echo -n "${MSG_BACKUP_CONFIRM_OVERWRITE:-Overwrite? y/N}: "
        local ans
        read -r ans
        [[ "$ans" =~ ^[Yy]$ ]] || { log_info "${MSG_BACKUP_CANCELLED:-Cancelled}"; return 0; }
    fi

    if [[ ! -d "$BACKUP_BIN_DIR" ]] || [[ ! -w "$BACKUP_BIN_DIR" ]]; then
        log_err "${MSG_BACKUP_BIN_NOT_WRITABLE:-Cannot write to}: $BACKUP_BIN_DIR"
        return 1
    fi

    log_step "${MSG_BACKUP_LAUNCH_WRITING:-Writing launcher} $launcher_path"

    # 用 heredoc 直接写脚本：proot-distro login + --shared-tmp，让容器看到外部 /tmp
    # "$@" 把启动器的额外参数透传给容器内命令
    # Heredoc-write the script: proot-distro login + --shared-tmp shares /tmp,
    # and "$@" forwards extra args from the launcher into the in-container command.
    {
        printf '%s\n' '#!/usr/bin/env bash'
        printf '%s\n' "# generated by xynrin v3.3.0 — proot launcher"
        printf '%s\n' "# distro: $distro"
        printf '%s\n' "# cmd:    $cmd"
        printf 'exec proot-distro login %q --shared-tmp -- %s "$@"\n' "$distro" "$cmd"
    } > "$launcher_path" || { log_err "${MSG_BACKUP_LAUNCH_WRITE_FAIL:-Write failed}"; return 1; }

    chmod +x "$launcher_path" 2>/dev/null || { log_err "chmod failed"; return 1; }

    log_ok "${MSG_BACKUP_LAUNCH_DONE:-Launcher ready}: ${BACKUP_LAUNCH_PREFIX}${raw_name}"
    log_info "${MSG_BACKUP_LAUNCH_TRY:-Try it now (any args go through):} ${BACKUP_LAUNCH_PREFIX}${raw_name}"
}

backup_launcher_remove() {
    # 不依赖 proot-distro 是否安装：用户可能想清理残留
    # Don't gate on proot-distro presence — user may want to clean up leftovers
    if [[ ! -d "$BACKUP_BIN_DIR" ]]; then
        log_warn "${MSG_BACKUP_BIN_MISSING:-Bin dir not found}: $BACKUP_BIN_DIR"
        return 0
    fi

    local found
    found="$(find "$BACKUP_BIN_DIR" -maxdepth 1 -type f -name "${BACKUP_LAUNCH_PREFIX}*" 2>/dev/null | sort)"
    if [[ -z "$found" ]]; then
        log_warn "${MSG_BACKUP_LAUNCH_NONE:-No xynrin-launch-* shortcuts found}"
        return 0
    fi

    local picked
    if command -v fzf &> /dev/null; then
        picked="$(echo "$found" | fzf --height=50% --reverse --no-info --border=rounded \
            --multi --prompt="${MSG_BACKUP_LAUNCH_PICK_DEL:-Pick launchers to remove (TAB to multi-select)} > ")" || return 0
    else
        echo "$found"
        echo -n "> "
        read -r picked
    fi
    [[ -z "$picked" ]] && return 0

    while IFS= read -r p; do
        [[ -z "$p" ]] && continue
        if rm -f "$p" 2>/dev/null; then
            log_ok "${MSG_BACKUP_LAUNCH_REMOVED:-Removed}: $(basename "$p")"
        else
            log_err "${MSG_BACKUP_LAUNCH_REMOVE_FAIL:-Remove failed}: $p"
        fi
    done <<< "$picked"
}
