#!/usr/bin/env bash
# tui/modules/bootstrap.sh - 首次部署：装依赖 + 可选 Ubuntu + 镜像自检
# First-time setup: deps + optional Ubuntu + mirror health check

set -uo pipefail
MODULE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$MODULE_DIR/_common.sh"

# 镜像源完整性自检：v3.1.0 损坏过 sources.list（只剩 termux-main）
# Mirror health check: v3.1.0 wrote a partial sources.list (only termux-main)
bootstrap_repair_mirror_if_broken() {
    local sources="$PREFIX/etc/apt/sources.list"
    local x11="$PREFIX/etc/apt/sources.list.d/x11.list"
    local root="$PREFIX/etc/apt/sources.list.d/root.list"
    local broken=0
    if [[ -f "$sources" ]] && grep -q "Auto-generated by xynrin" "$sources" 2>/dev/null; then
        [[ ! -s "$x11"  ]] && broken=1
        [[ ! -s "$root" ]] && broken=1
    fi
    if [[ $broken -eq 1 ]]; then
        log_warn "${MSG_MIRROR_REPAIR:-Detected broken mirror, resetting to official}"
        load_module mirror 2>/dev/null || source "$MODULE_DIR/mirror.sh"
        apply_mirror "https://packages.termux.dev/apt/termux-main" "Official" >/dev/null 2>&1 || \
            log_warn "mirror auto-repair failed"
    fi
}

bootstrap_action() {
    log_info "${MSG_BOOTSTRAP_TITLE:-First-time setup}"

    bootstrap_repair_mirror_if_broken

    log_step "${MSG_BOOTSTRAP_PKG_UPDATE:-Updating package index}"
    pkg update -y || log_warn "pkg update had warnings"

    # 关键依赖：curl/git 是 bootstrap 自身要的；fzf/ncurses-utils 是 TUI 要的；
    # proot-distro 留给真正用容器的用户安装
    # Core deps: curl/git for bootstrap itself; fzf/ncurses-utils for the TUI;
    # proot-distro is now lazy-installed only when the user picks option 2.
    log_step "${MSG_BOOTSTRAP_PKG_INSTALL:-Installing dependencies}"
    pkg install -y curl git wget fzf ncurses-utils || {
        log_err "core dependency install failed"
        return 1
    }

    log_ok "${MSG_BOOTSTRAP_DONE:-Setup complete}"
    log_info "${MSG_BOOTSTRAP_HINT_DISTRO:-Tip: run option 2 to install a Linux distro on demand}"
}
