#!/usr/bin/env bash
# tui/modules/mirror.sh - APT 镜像源切换 / Termux APT mirror

set -uo pipefail
MODULE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$MODULE_DIR/_common.sh"

mirror_action() {
    local options=(
        "1) ${MSG_MIRROR_TSINGHUA:-Tsinghua}"
        "2) ${MSG_MIRROR_USTC:-USTC}"
        "3) ${MSG_MIRROR_OFFICIAL:-Official}"
        "0) ${OPT_BACK:-Back}"
    )
    log_info "${MSG_MIRROR_TITLE:-Mirror}"
    local picked
    if command -v fzf &> /dev/null; then
        picked="$(printf '%s\n' "${options[@]}" | fzf --height=40% --reverse --no-info --border=rounded \
            --prompt="mirror > ")" || return 0
    else
        printf '  %s\n' "${options[@]}"
        echo -n "> "
        read -r raw
        picked="${raw}) "
    fi
    case "$picked" in
        1*) apply_mirror "https://mirrors.tuna.tsinghua.edu.cn/termux" "Tsinghua" ;;
        2*) apply_mirror "https://mirrors.ustc.edu.cn/termux"          "USTC" ;;
        3*) apply_mirror "https://packages.termux.dev/apt/termux-main" "Official" ;;
        0*|"") return 0 ;;
        *) log_warn "${MSG_INVALID_CHOICE:-Invalid choice}" ;;
    esac
}

# 写入完整的 sources.list（包含 main / x11 / root，与官方默认一致）
# Write a full sources.list (main + x11 + root, matching official layout).
# 镜像站把 main / x11 / root 三个仓库放在同一个根路径下；
# 官方仓库则各自有不同的 URL（packages.termux.dev/apt/<repo>）。
# Mirrors host main/x11/root under one root path; the official repo
# uses separate URLs per repo (packages.termux.dev/apt/<repo>).
apply_mirror() {
    local base="$1" name="$2"
    local sources="$PREFIX/etc/apt/sources.list"
    local x11_list="$PREFIX/etc/apt/sources.list.d/x11.list"
    local root_list="$PREFIX/etc/apt/sources.list.d/root.list"

    log_step "${MSG_MIRROR_APPLYING:-Applying} $name"

    if [[ -f "$sources" ]]; then
        cp "$sources" "${sources}.bak.$(date +%s)" 2>/dev/null || \
            log_warn "${MSG_MIRROR_BACKUP_WARN:-backup failed}"
    fi
    mkdir -p "$PREFIX/etc/apt/sources.list.d"

    if [[ "$name" == "Official" ]]; then
        cat > "$sources" <<EOF
# Auto-generated by xynrin
deb https://packages.termux.dev/apt/termux-main stable main
EOF
        cat > "$x11_list" <<'EOF'
deb https://packages.termux.dev/apt/termux-x11 x11 main
EOF
        cat > "$root_list" <<'EOF'
deb https://packages.termux.dev/apt/termux-root root stable
EOF
    else
        # 镜像站用统一根路径 / mirror sites use one root for all three repos
        cat > "$sources" <<EOF
# Auto-generated by xynrin
deb ${base}/apt/termux-main stable main
EOF
        cat > "$x11_list" <<EOF
deb ${base}/apt/termux-x11 x11 main
EOF
        cat > "$root_list" <<EOF
deb ${base}/apt/termux-root root stable
EOF
    fi

    log_ok "${MSG_MIRROR_APPLIED:-Applied}: $name"
    log_step "${MSG_MIRROR_UPDATING:-Updating index}"
    pkg update -y || log_warn "${MSG_MIRROR_UPDATE_WARN:-index update failed}"
}
