#!/usr/bin/env bash
# tui/modules/x11/install.sh - 安装 termux-x11 + 桌面 (xfce4 / lxqt) + 写 start-desktop
# Install termux-x11 + desktop (xfce4/lxqt) + write start-desktop launcher

# $1 = "xfce4" 或 "lxqt"
x11_install() {
    local desktop="${1:-xfce4}"
    local session_cmd
    case "$desktop" in
        xfce4) session_cmd="xfce4-session" ;;
        lxqt)  session_cmd="startlxqt" ;;
        *)
            log_err "${MSG_X11_BAD_DESKTOP:-Unknown desktop:} $desktop"
            return 1
            ;;
    esac

    log_info "${MSG_X11_START:-Setting up X11 + desktop} ($desktop)"

    # 1) termux-x11-nightly —— Termux 默认仓库已有
    # termux-x11-nightly is in the default Termux repo
    log_step "${MSG_X11_INSTALL_X11:-Installing termux-x11-nightly}"
    if ! pkg install -y termux-x11-nightly 2>&1; then
        log_err "${MSG_X11_X11_FAIL:-termux-x11-nightly install failed}"
        log_info "${MSG_X11_X11_HINT:-Install the Termux:X11 APK from GitHub (must match Termux package name) then retry}"
        return 1
    fi
    if ! command -v termux-x11 &> /dev/null; then
        log_warn "${MSG_X11_NO_BIN:-termux-x11 binary not found after install}"
        log_info "${MSG_X11_X11_HINT:-Install the Termux:X11 APK from GitHub (must match Termux package name) then retry}"
    fi

    # 2) 音频 + dbus / audio + dbus
    log_step "${MSG_X11_INSTALL_AUDIO:-Installing pulseaudio + dbus}"
    if ! pkg install -y pulseaudio dbus 2>&1; then
        log_err "${MSG_X11_AUDIO_FAIL:-pulseaudio/dbus install failed}"
        return 1
    fi

    # 3) 桌面环境 / desktop environment
    log_step "${MSG_X11_INSTALL_DE:-Installing desktop} ($desktop)"
    if ! pkg install -y "$desktop" 2>&1; then
        log_err "${MSG_X11_DE_FAIL:-desktop install failed} ($desktop)"
        return 1
    fi

    # 4) 写 start-desktop / write start-desktop
    log_step "${MSG_X11_WRITE_LAUNCHER:-Writing $X11_LAUNCHER}"
    mkdir -p "$(dirname "$X11_LAUNCHER")"
    cat > "$X11_LAUNCHER" <<EOF
#!/data/data/com.termux/files/usr/bin/bash
# start-desktop - 由 xynrin 生成 / generated by xynrin
# 用法 / usage: start-desktop
# 然后切到 Termux:X11 app 看桌面 / then switch to Termux:X11 app to see the desktop
set -u

# 1) pulseaudio (idle 不退出，让桌面音频常驻)
# pulseaudio (never idle out, keep desktop audio alive)
pulseaudio --start --exit-idle-time=-1 2>/dev/null || true
export PULSE_SERVER=127.0.0.1

# 2) 杀旧 termux-x11 进程，避免端口/socket 冲突
# kill stale termux-x11 to avoid socket conflict
pkill -9 termux-x11 2>/dev/null || true

# 3) 后台启 termux-x11 监听 :0
# launch termux-x11 in background on display :0
termux-x11 :0 -ac &

# 4) 等 X server 起来 / wait for X server
sleep 1

# 5) 启动桌面会话 / launch desktop session
export DISPLAY=:0
env DISPLAY=:0 dbus-launch --exit-with-session ${session_cmd} &

echo "[xynrin] ${desktop} 已启动 / launched - 切到 Termux:X11 app 查看桌面"
echo "[xynrin] switch to the Termux:X11 app to see the desktop"
EOF
    chmod +x "$X11_LAUNCHER"

    log_ok "${MSG_X11_DONE:-X11 + desktop ready}"
    log_info "${MSG_X11_RUN_HINT:-Run 'start-desktop' to launch}"
    log_info "${MSG_X11_APK_HINT:-You must also install the Termux:X11 APK from F-Droid}"
}
